### ISSUE TITLE
Nothing is in the repository

### ISSUE THREAD

**Issue by yasuharu519** [lotz84/sawada-fanclub#1]
埋めていきたい

**Comment by e-jigsaw** [comment]
in English PLEASE???

**Comment by yasuharu519** [comment]
新手の煽りだ

**Comment by lotz84** [comment]
I guess Sawada becomes world-renowned engineer. Therefore we are better to use English in this repo.

**Comment by yasuharu519** [comment]
Oh, ok. My point was it says "fanclub", but nothing was there. I thought that was problem, but now it is not, so i will close this issue.
