### ISSUE TITLE
No update on the wight graph.

### ISSUE THREAD

**Issue by lotz84** [lotz84/sawada-fanclub#5]
The last update is Oct 22, 2014.
@yasuharu519

**Comment by e-jigsaw** [comment]
We want to know latest weight!

**Comment by kaelaela** [comment]
![heavy](http://i.imgur.com/3HNWO99.jpg)

**Comment by laysakura** [comment]
+1

**Comment by lotz84** [comment]
@yasuharu519 Is there any API for getting your realtime weight data?

**Comment by e-jigsaw** [comment]
warota
